### ISSUE TITLE
Got a SIGABRT when using RM_CreatePosition()

### ISSUE THREAD

**Issue by Violin9906** [esmini/esmini#279]
I got an error when a program using RM_CreatePosition() exit. It said:
```
malloc_consolidate(): invalid chunk size

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

It happened just after the scenario was DONE and the program was going to exit. It seems that this happens when:
- the program includes a class calls `RM_CreatePosition()` (not matter whether the class is instantiated or not)
- esmini is initialize with display on
- `SE_Close()` is called in the main function.

I've created a [repository](https://github.com/Violin9906/esmini-issue--279) which can reproduce this issue.

For your reference, I've use gdb debug the program, and the backtraces are listed below:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5ad8859 in __GI_abort () at abort.c:79
#2  0x00007ffff5b4329e in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff5c6d298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff5b4b32c in malloc_printerr (
    str=str@entry=0x7ffff5c6f278 "malloc_consolidate(): invalid chunk size")
    at malloc.c:5347
#4  0x00007ffff5b4bb08 in malloc_consolidate (
    av=av@entry=0x7ffff5ca2b80 <main_arena>) at malloc.c:4477
#5  0x00007ffff5b4d010 in _int_free (av=0x7ffff5ca2b80 <main_arena>, 
    p=0x555556398270, have_lock=<optimized out>) at malloc.c:4400
#6  0x00007ffff2f0d585 in ?? ()
   from /lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01
#7  0x00007ffff2fd4d96 in ?? ()
   from /lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01
#8  0x00007ffff2fd5d6c in ?? ()
   from /lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01
#9  0x00007ffff2fada58 in ?? ()
   from /lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01
#10 0x00007ffff2fb08b8 in ?? ()
   from /lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01
#11 0x00007ffff46e19fa in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#12 0x00007ffff46e21af in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00007ffff7ffd060 in ?? () from /lib64/ld-linux-x86-64.so.2
#14 0x0000000000000000 in ?? ()
```

I'm using Ubuntu 20.04, the graphics card is GTX 1070 and the driver is NVIDIA driver metapackage nvidia-driver-470. The esmini shared libs are built from esmini release v2.23.0

**Comment by Violin9906** [comment]
It seems that any function in RM lib can cause this issue. So I guess the link of libesminiRMLib.so causes this?

**Comment by Violin9906** [comment]
I've test the program on another computer without graphics card, and it works well.
