### ISSUE TITLE
Unit-tests segfault when run in container

### ISSUE THREAD

**Issue by cassava** [esmini/esmini#554]
This is with the most recently released version of esmini, 2.37.4.

When building and testing esmini in a container, with Ubuntu 22.04, the following unit tests fail:

```
98% tests passed, 5 tests failed out of 263

Total Test time (real) =  95.41 sec

The following tests FAILED:
	142 - ScenarioPlayer_test (Failed)
	143 - CustomCameraTest.TestCustomCameraVariants (Failed)
	147 - Controllers.TestSeparateControllersOnLatLong (Failed)
	148 - ScenarioEngineDll_test (SEGFAULT)
	211 - APITest.TestFetchImage (SEGFAULT)
```

I looked into one of them, namely 147, the output is:

```
147/263 Test: Controllers.TestSeparateControllersOnLatLong
Command: "/src/esmini/build/EnvironmentSimulator/Unittest/ScenarioPl
ayer_test" "--gtest_filter=Controllers.TestSeparateControllersOnLatLong"
Directory: /src/esmini/build/EnvironmentSimulator/Unittest
"Controllers.TestSeparateControllersOnLatLong" start time: Mar 26 10:34 UTC
Output:
----------------------------------------------------------
Note: Google Test filter = Controllers.TestSeparateControllersOnLatLong
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Controllers
[ RUN      ] Controllers.TestSeparateControllersOnLatLong
No protocol specified
No protocol specified
No protocol specified
No protocol specified
/src/esmini/EnvironmentSimulator/Unittest/ScenarioPlayer_test.cpp:38
4: Failure
Expected equality of these values:
  retval
    Which is: -1
  0
[  FAILED  ] Controllers.TestSeparateControllersOnLatLong (44 ms)
[----------] 1 test from Controllers (44 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (44 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Controllers.TestSeparateControllersOnLatLong

 1 FAILED TEST
<end of output>
Test time =   0.06 sec
----------------------------------------------------------
Test Failed.
"Controllers.TestSeparateControllersOnLatLong" end time: Mar 26 10:34 UTC
"Controllers.TestSeparateControllersOnLatLong" time elapsed: 00:00:00
----------------------------------------------------------
```

The code at the point where the test is failing is:

```cpp
TEST(Controllers, TestSeparateControllersOnLatLong)
{
    const char*     args[] = {"esmini",
                              "--osc",
                              "../../../EnvironmentSimulator/Unittest/xosc/acc_with_interactive_steering.xosc",
                              "--window",
                              "60",
                              "60",
                              "800",
                              "600",
                              "--headless",
                              "--disable_stdout"};
    int             argc   = sizeof(args) / sizeof(char*);
    double          dt     = 0.1f;
    ScenarioPlayer* player = new ScenarioPlayer(argc, const_cast<char**>(args));

    ASSERT_NE(player, nullptr);
    int retval = player->Init();
    ASSERT_EQ(retval, 0);
```

If I run this command on the commandline, esmini segfaults actually.
If I run the command without the `--window 60 60 800 600` argument, it goes through just fine.

I ran the command through gdb to see why it's segfaulting, and I get the following:

```
$ gdb --args ./esmini --osc ../EnvironmentSimulator/Unittest/xosc/acc_with_interactive_steering.xosc --window 60 60 800 600 --headless
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./esmini...
(gdb) run
Starting program: /src/esmini/bin/esmini --osc ../EnvironmentSimulator/Unittest/xosc/acc_with_interactive_steering.xosc --window 60 60 800 600 --headless
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
esmini GIT REV: N/A
esmini GIT TAG: N/A
esmini GIT BRANCH: N/A
esmini BUILD VERSION: N/A - client build
No fixed timestep specified - running in realtime speed
Generated seed 542974918
Loading ../EnvironmentSimulator/Unittest/xosc/./acc_with_interactive_steering.xosc (v1.3)
0 variables
Unsupported geo reference attr: +no_defs
Loaded OpenDRIVE: ../EnvironmentSimulator/Unittest/xosc/./../../../resources/xodr/straight_500m.xodr
Expr ${250/3.6} = 250/3.6 = 69.4444444444
0 parameters
No protocol specified
No protocol specified
0.000: Viewer failure. Probably requested level of Anti Aliasing (4 multisamples) is not supported. Making another attempt without Anti-Alias and on first screen.
No protocol specified
No protocol specified
0.000: Failed 2nd attempt to create viewer, giving up. Try --headless option to run without viewer
0.000: Viewer initialization failed

Program received signal SIGSEGV, Segmentation fault.
0x000055caf8f94e4d in osgViewer::ViewerBase::setDone (this=0x0, done=true) at /src/esmini/externals/osg/linux/include/osgViewer/ViewerBase:136
136	        void setDone(bool done) { _done = done; }
(gdb) bt
#0  0x000055caf8f94e4d in osgViewer::ViewerBase::setDone (this=0x0, done=true)
    at /src/esmini/externals/osg/linux/include/osgViewer/ViewerBase:136
#1  0x000055caf8f7f10c in viewer::Viewer::~Viewer (this=0x55cafbe9d5e0, __in_chrg=<optimized out>)
    at /src/esmini/EnvironmentSimulator/Modules/ViewerBase/viewer.cpp:1971
#2  0x000055caf8d957cd in scenarioengine::ScenarioPlayer::CloseViewer (this=0x55cafbe890c0)
    at /src/esmini/EnvironmentSimulator/Modules/PlayerBase/playerbase.cpp:657
#3  0x000055caf8d93050 in scenarioengine::ScenarioPlayer::~ScenarioPlayer (this=0x55cafbe890c0, __in_chrg=<optimized out>)
    at /src/esmini/EnvironmentSimulator/Modules/PlayerBase/playerbase.cpp:106
#4  0x000055caf8d8e21e in std::default_delete<scenarioengine::ScenarioPlayer>::operator() (this=0x7fff8f64e588, __ptr=0x55cafbe890c0)
    at /usr/include/c++/11/bits/unique_ptr.h:85
#5  0x000055caf8d8c356 in std::unique_ptr<scenarioengine::ScenarioPlayer, std::default_delete<scenarioengine::ScenarioPlayer> >::~unique_ptr (
    this=0x7fff8f64e588, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/unique_ptr.h:361
#6  0x000055caf8d892fd in execute_scenario (argc=9, argv=0x7fff8f64e778)
    at /src/esmini/EnvironmentSimulator/Applications/esmini/main.cpp:112
#7  0x000055caf8d895a1 in main (argc=9, argv=0x7fff8f64e778)
    at /src/esmini/EnvironmentSimulator/Applications/esmini/main.cpp:121
(gdb)
```

There are a few things I don't quite understand:

1. The output suggests to use `--headless` to run without viewer.
   That argument *is* provided, so perhaps the `--window` argument is overriding the `--headless` argument?
2. Are these arguments are mutually exclusive? If so, why is the test using them?
3. Can we make having a GUI-capable environment a pre-condition for running tests that need them, so that building and testing esmini in a CI environment works?
4. Why are we disabling stdout output for unit-tests? It seems to me that seeing the output would be helpful when trying to debug failed tests.

**Comment by eknabevcc** [comment]
Thanks for detailed report. 

1. --headless means running without screen window
2. --window x y w h means running with a window (off-screen or on screen, depending on --headless or not)
3.  With GUI I assume you mean X Windows env. esmini can utilize off screen rendering via MesaGL if gfx hw is missing. 
4. Simply to avoid mega-polluted test logs. It's very easy to activate std output. Just define LOG_TO_CONSOLE (see bottom of each unit test module). 

What is the latest version you run tests successfully? Was it 2.37.3?
Can you provide more info about your container environment/setup? Then perhaps we can reproduce.

**Comment by eknabevcc** [comment]
Meanwhile: 

First a clarification: MesaGL should be an automatic fallback rendering pipeline in case of missing system gfx support. See brief info here: [User guide - Software rendering](https://esmini.github.io/#_software_rendering_no_gfx_hw).

BTW: Did you install prerequisites according to: [User guide - Build esmini - quick guide](https://esmini.github.io/#_build_esmini_quick_guide) (sudo apt install ...) 

It would be great if you could get the rendering to work in your container. But, as a last resort if it fails, you can very well configure esmini for slim headless operation, i.e. without support for graphics altogether. In that configuration all test cases that depends on graphics (e.g. pixel checks) will be skipped automatically. See USE_OSG directive in [User guide - Slim esmini - customize configration](https://esmini.github.io/#_slim_esmini_customize_configration). 

The seg fault we have potentially solved by commit 881b732ec54ec851a7a46f9ad9f8143971c450d1 (assuming it's a side effect of viewer creation failure).

I'd still like some more info on how to reproduce your container setup, to investigate the failing sw-based rendering pipeline.
